"""tools/export.py — Export recipes to PDF and image formats."""

import io
import re
from datetime import datetime
from typing import Dict, Any, Optional
from PIL import Image, ImageDraw, ImageFont
import textwrap


class RecipeExporter:
    """Export recipes to various formats."""
    
    def __init__(self):
        self.fonts = {}
    
    def _get_font(self, size: int, bold: bool = False) -> ImageFont.FreeTypeFont:
        """Get font for PIL image generation."""
        try:
            if bold:
                font_path = "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf"
            else:
                font_path = "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf"
            return ImageFont.truetype(font_path, size)
        except:
            return ImageFont.load_default()
    
    def to_pdf(self, recipe_name: str, recipe_text: str,
               nutrition_data: Dict = None, budget_data: Dict = None) -> bytes:
        """Generate PDF recipe card."""
        try:
            from reportlab.lib.pagesizes import A4
            from reportlab.lib.colors import HexColor, white
            from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
            from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
            from reportlab.lib.units import mm
            
            buf = io.BytesIO()
            doc = SimpleDocTemplate(buf, pagesize=A4, topMargin=15*mm,
                                    bottomMargin=15*mm, leftMargin=20*mm, rightMargin=20*mm)
            
            styles = getSampleStyleSheet()
            orange = HexColor("#e8541e")
            dark = HexColor("#1a1a18")
            
            title_style = ParagraphStyle(
                "title", fontSize=22, textColor=orange,
                spaceAfter=6, fontName="Helvetica-Bold"
            )
            heading_style = ParagraphStyle(
                "heading", fontSize=13, textColor=dark,
                spaceAfter=4, spaceBefore=8, fontName="Helvetica-Bold"
            )
            body_style = ParagraphStyle(
                "body", fontSize=9, textColor=dark,
                spaceAfter=3, leading=12
            )
            
            story = []
            
            # Title
            story.append(Paragraph(f"🍳 {recipe_name}", title_style))
            story.append(Paragraph(f"Generated by NutriBot on {datetime.now().strftime('%B %d, %Y')}",
                                  body_style))
            story.append(Spacer(1, 5*mm))
            
            # Extract sections
            sections = self._extract_sections(recipe_text)
            
            # Ingredients
            if sections.get("ingredients"):
                story.append(Paragraph("📋 Ingredients", heading_style))
                for ing in sections["ingredients"][:15]:
                    story.append(Paragraph(f"• {ing}", body_style))
                story.append(Spacer(1, 3*mm))
            
            # Instructions
            if sections.get("instructions"):
                story.append(Paragraph("👨‍🍳 Instructions", heading_style))
                for i, step in enumerate(sections["instructions"][:12], 1):
                    step_text = f"{i}. {step[:100]}"
                    story.append(Paragraph(step_text, body_style))
                story.append(Spacer(1, 3*mm))
            
            # Nutrition table
            if nutrition_data and nutrition_data.get("per_serving"):
                story.append(Paragraph("📊 Nutrition (per serving)", heading_style))
                ps = nutrition_data["per_serving"]
                data = [
                    ["Calories", f"{ps.get('calories', 0):.0f} kcal"],
                    ["Protein", f"{ps.get('protein_g', 0):.0f}g"],
                    ["Carbs", f"{ps.get('carbs_g', 0):.0f}g"],
                    ["Fat", f"{ps.get('fat_g', 0):.0f}g"],
                    ["Fiber", f"{ps.get('fiber_g', 0):.0f}g"],
                ]
                table = Table(data, colWidths=[40*mm, 40*mm])
                table.setStyle(TableStyle([
                    ('FONTNAME', (0,0), (-1,-1), 'Helvetica'),
                    ('FONTSIZE', (0,0), (-1,-1), 9),
                    ('BACKGROUND', (0,0), (0,-1), HexColor("#f8f8f8")),
                    ('GRID', (0,0), (-1,-1), 0.5, HexColor("#e2e8f0")),
                ]))
                story.append(table)
            
            # Budget
            if budget_data:
                story.append(Spacer(1, 3*mm))
                story.append(Paragraph("💰 Cost Breakdown", heading_style))
                cur = budget_data.get("currency", "₹")
                story.append(Paragraph(f"Total: {cur}{budget_data.get('total_cost', 0):.0f}", body_style))
                story.append(Paragraph(f"Per Serving: {cur}{budget_data.get('per_serving', 0):.0f}", body_style))
            
            doc.build(story)
            buf.seek(0)
            return buf.getvalue()
            
        except ImportError:
            return self._simple_pdf_fallback(recipe_name, recipe_text)
    
    def to_image(self, recipe_name: str, recipe_text: str,
                 nutrition_data: Dict = None, eco_score: Dict = None) -> bytes:
        """Generate shareable recipe card image."""
        # Create image
        img = Image.new('RGB', (800, 1000), color='#fafaf7')
        draw = ImageDraw.Draw(img)
        
        # Fonts
        title_font = self._get_font(32, bold=True)
        heading_font = self._get_font(24, bold=True)
        body_font = self._get_font(18)
        small_font = self._get_font(14)
        
        y = 20
        
        # Header
        draw.rectangle([0, 0, 800, 80], fill='#e8541e')
        draw.text((20, 25), "🥗 NutriBot", fill='white', font=title_font)
        
        y = 100
        
        # Recipe name
        wrapped_name = textwrap.wrap(recipe_name, width=25)
        for line in wrapped_name:
            draw.text((20, y), line, fill='#1a1a18', font=title_font)
            y += 45
        
        y += 20
        
        # Nutrition
        if nutrition_data and nutrition_data.get("per_serving"):
            ps = nutrition_data["per_serving"]
            draw.text((20, y), "📊 Nutrition (per serving)", fill='#e8541e', font=heading_font)
            y += 35
            
            metrics = [
                f"🔥 {ps.get('calories', 0):.0f} kcal",
                f"💪 {ps.get('protein_g', 0):.0f}g protein",
                f"🍚 {ps.get('carbs_g', 0):.0f}g carbs",
                f"🥑 {ps.get('fat_g', 0):.0f}g fat",
            ]
            
            for metric in metrics:
                draw.text((20, y), metric, fill='#64748b', font=body_font)
                y += 28
        
        y += 20
        
        # Eco score
        if eco_score:
            score = eco_score.get('score', 0)
            grade = eco_score.get('grade', '?')
            color = '#2ecc71' if score >= 70 else '#e8541e' if score >= 50 else '#e74c3c'
            draw.text((20, y), f"🌱 Eco Score: {score:.0f}/100 (Grade {grade})", 
                     fill=color, font=body_font)
            y += 40
        
        # Divider
        draw.line([(20, y), (780, y)], fill='#e2e8f0', width=1)
        y += 20
        
        # Instructions preview
        sections = self._extract_sections(recipe_text)
        if sections.get("instructions"):
            draw.text((20, y), "👨‍🍳 Quick Instructions", fill='#e8541e', font=heading_font)
            y += 35
            
            for i, step in enumerate(sections["instructions"][:3], 1):
                step_text = f"{i}. {step[:60]}..."
                draw.text((20, y), step_text, fill='#4a4a48', font=small_font)
                y += 25
        
        # Footer
        draw.rectangle([0, 920, 800, 1000], fill='#1a1a18')
        draw.text((20, 940), "Powered by AI | NutriBot", fill='#888888', font=small_font)
        draw.text((20, 965), "Your Personal Nutrition Assistant", fill='#666666', font=small_font)
        
        # Save to bytes
        buf = io.BytesIO()
        img.save(buf, format='PNG', optimize=True)
        buf.seek(0)
        return buf.getvalue()
    
    def _extract_sections(self, text: str) -> Dict[str, list]:
        """Extract ingredients and instructions sections."""
        sections = {"ingredients": [], "instructions": []}
        
        # Extract ingredients
        ing_match = re.search(r'###\s*📋 Ingredients\s*\n(.*?)(?=\n###|\n##|$)', text, re.DOTALL)
        if ing_match:
            ing_text = ing_match.group(1)
            for line in ing_text.split('\n'):
                line = line.strip()
                if line and line[0] in ['-', '•', '*']:
                    sections["ingredients"].append(line[1:].strip())
                elif line and re.match(r'^\d+', line):
                    sections["ingredients"].append(line)
        
        # Extract instructions
        inst_match = re.search(r'###\s*👨‍🍳 Instructions\s*\n(.*?)(?=\n###|\n##|$)', text, re.DOTALL)
        if inst_match:
            inst_text = inst_match.group(1)
            for line in inst_text.split('\n'):
                line = line.strip()
                if line and re.match(r'^\d+\.', line):
                    sections["instructions"].append(line)
        
        return sections
    
    def _simple_pdf_fallback(self, recipe_name: str, recipe_text: str) -> bytes:
        """Simple PDF fallback when reportlab is not available."""
        content = f"""NutriBot Recipe
================
{recipe_name}
Generated: {datetime.now().strftime('%Y-%m-%d')}

{recipe_text[:5000]}
        """
        return content.encode('utf-8')
    
    def to_markdown(self, recipe_name: str, recipe_text: str,
                    nutrition_data: Dict = None) -> str:
        """Export recipe as markdown."""
        lines = [
            f"# 🍳 {recipe_name}",
            "",
            f"*Generated by NutriBot on {datetime.now().strftime('%B %d, %Y')}*",
            "",
        ]
        
        if nutrition_data and nutrition_data.get("per_serving"):
            lines.append("## 📊 Nutrition (per serving)")
            ps = nutrition_data["per_serving"]
            lines.append("| Nutrient | Amount |")
            lines.append("|----------|--------|")
            lines.append(f"| Calories | {ps.get('calories', 0):.0f} kcal |")
            lines.append(f"| Protein | {ps.get('protein_g', 0):.0f}g |")
            lines.append(f"| Carbs | {ps.get('carbs_g', 0):.0f}g |")
            lines.append(f"| Fat | {ps.get('fat_g', 0):.0f}g |")
            lines.append(f"| Fiber | {ps.get('fiber_g', 0):.0f}g |")
            lines.append("")
        
        # Add recipe text (clean markdown)
        lines.append(recipe_text)
        
        lines.append("")
        lines.append("---")
        lines.append("*Made with ❤️ by NutriBot*")
        
        return "\n".join(lines)


# Convenience functions
def export_recipe_to_pdf(recipe_name: str, recipe_text: str,
                         nutrition_data: Dict = None, budget_data: Dict = None) -> bytes:
    """Export recipe to PDF."""
    exporter = RecipeExporter()
    return exporter.to_pdf(recipe_name, recipe_text, nutrition_data, budget_data)


def export_recipe_to_image(recipe_name: str, recipe_text: str,
                           nutrition_data: Dict = None, eco_score: Dict = None) -> bytes:
    """Export recipe to image card."""
    exporter = RecipeExporter()
    return exporter.to_image(recipe_name, recipe_text, nutrition_data, eco_score)


def export_recipe_to_markdown(recipe_name: str, recipe_text: str,
                              nutrition_data: Dict = None) -> str:
    """Export recipe to markdown."""
    exporter = RecipeExporter()
    return exporter.to_markdown(recipe_name, recipe_text, nutrition_data)
